archetypeDir           = "archetypes"
author                 = "Giao Chan Fong"
baseUrl                = "https://filosofiaparanoobs.github.io/"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "pixyll"
themesDir              = "themes"
title                  = "Filosofía para noobs | hugo-theme-pixyll"
enableEmoji            = true
DefaultContentLanguage = "en"
#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

[Languages.ru]
weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  search_engine = false
  #google_analytics_id = ""
  twitter_username = "username"
  paginate = 5
