languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://filosofiaparanoobs.github.io/"
canonifyurls = true
title = "Filosofia para noobs"
author = "admin"
theme = "pixyll"
disqusShortname = "sitename"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  #search_engine = false | commented to disable search bar 
  #google_analytics_id = "XX-XXXXXXXX-X" | Not using google_analytics for the moment
  #twitter_username = "username" | Not using Twitter for the moment
  paginate = 5